[package]
name = "axum-typed-routing"
version = "0.4.0"
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["axum", "routing", "handler", "typed", "macro"]
categories = ["web-programming"]
description = "Typed routing macros for axum"
homepage = "https://github.com/jvdwrf/axum-typed-routing"
repository = "https://github.com/jvdwrf/axum-typed-routing"
readme = "../README.md"

[package.metadata.docs.rs]
features = ["aide"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum.workspace = true
aide = { workspace = true, optional = true }
axum-typed-routing-macros = { version = "0.3.0", path = "../axum-typed-routing-macros" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
axum-test = { version = "18", features = [] }
serde.workspace = true
schemars.workspace = true

[features]
aide = ["dep:aide"]
