[package]
name = "axum-typed-routing-macros"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["axum", "routing", "handler", "typed", "macro"]
categories = ["web-programming"]
description = "Typed routing macros for axum"
homepage = "https://github.com/jvdwrf/axum-typed-routing"
repository = "https://github.com/jvdwrf/axum-typed-routing"
readme = "../README.md"

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
axum.workspace = true
aide.workspace = true
serde.workspace = true
schemars.workspace = true
axum-typed-routing = { path = "../axum-typed-routing" }

[lib]
proc-macro = true
